# Jekyll config
exclude:
- Gemfile
- Gemfile.lock
- Guardfile
- Rakefile
- galleries
- scripts

permalink: ./:year-:month-:day-:title.html
url: http://detunized.net/new_blog
paginate: 15

# Custom site config
name: Detunized Gravy
author:
    name: Dmitry Yakimenko
    email: detunized.spam@gmail.com
