# Jekyll config
exclude:
    - Gemfile
    - Gemfile.lock
    - Guardfile
    - Rakefile
    - galleries
    - scripts
    - vendor

plugins:
    - jekyll-paginate

permalink: html/:year-:month-:day-:title.html
url: https://detunized.net
image_host: https://raw.seedhost.eu/detunized/detunized.net
paginate: 15

# Custom site config
name: Detunized Gravy
author:
    name: Dmitry Yakimenko
    email: detunized.spam@gmail.com
